name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create Release with assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            manifest.json
            theme.css
            CHANGELOG.md
          draft: false
          prerelease: false
          generate_release_notes: true
