name: Build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Upload theme artifacts
        uses: actions/upload-artifact@v4
        with:
          name: theme-files
          path: |
            manifest.json
            theme.css
            CHANGELOG.md
          if-no-files-found: error
